# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mao2JkPbgzO-1Iw9ZoLOIYPMM-7nMoEb
"""

# app.py

import streamlit as st
from aidocmate import get_prediction, helper

st.set_page_config(page_title="Health Predictor", page_icon="🩺", layout="centered")

st.title("🩺 AI Health Assistant")
st.markdown("**Enter your symptoms and get possible diagnosis with medical advice.**")

# List of possible symptoms (you can load dynamically from your dataset)
all_symptoms = ['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo']

selected_symptoms = st.multiselect("🔍 Select your symptoms", all_symptoms)

if st.button("Predict Disease"):
    if not selected_symptoms:
        st.warning("⚠️ Please select at least one symptom.")
    else:
        with st.spinner("Analyzing symptoms..."):
            disease = get_prediction(selected_symptoms)
            desc, precaution, medicine, diet, workout, symptoms, doctor = helper(disease)

        st.success(f"✅ Predicted Disease: **{disease}**")

        with st.expander("🧾 Description"):
            st.write(desc)

        with st.expander("💊 Medicines"):
            st.write(", ".join(medicine))

        with st.expander("🛡️ Precautions"):
            st.write(", ".join(precaution))

        with st.expander("🥗 Diet Recommendations"):
            st.write(", ".join(diet))

        with st.expander("🏋️ Workout Suggestions"):
            st.write(", ".join(workout))

        with st.expander("🧠 Related Symptoms"):
            st.write(", ".join(symptoms))

        st.info(f"👨‍⚕️ Suggested: {doctor}")